- name: et permissions on ~/.ssh
  file:
    path: "{{ lookup('env', 'HOME') + '/.ssh' }}"
    state: directory
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    recurse: true 
    mode: '0700'

- name: Set permissions for ~/.ssh files
  file:
    path: "{{ item }}"
    mode: '0600'
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*"

- name: Setup and start ssh-agent
  shell: |
    ssh-add
    eval "$(ssh-agent)"
